apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      nodeName: worker-2
      containers:
      - name: flask
        image: slimayadi/movie4u_flask:latest  # Update with the correct image tag
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: flask-code
          mountPath: /app
      volumes:
      - name: flask-code
        persistentVolumeClaim:
          claimName: flask-code-pvc

