apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Match the storage capacity with the PersistentVolume

